// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhQh-rXc4SUwoshYAo2gEcRHi8aQQjUnQ',
    appId: '1:552359783668:web:7ae5bc63cfb1df470902a1',
    messagingSenderId: '552359783668',
    projectId: 'ymkstore-1f8b8',
    authDomain: 'ymkstore-1f8b8.firebaseapp.com',
    databaseURL: 'https://ymkstore-1f8b8-default-rtdb.firebaseio.com',
    storageBucket: 'ymkstore-1f8b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn7ioChRCvjo1MzoMKwDDVVSibudNBmVY',
    appId: '1:552359783668:android:9d84362e33e390fb0902a1',
    messagingSenderId: '552359783668',
    projectId: 'ymkstore-1f8b8',
    databaseURL: 'https://ymkstore-1f8b8-default-rtdb.firebaseio.com',
    storageBucket: 'ymkstore-1f8b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7D84S24BELMiqOsDteZ-HURA5aEMml4',
    appId: '1:552359783668:ios:d4308d45514149e30902a1',
    messagingSenderId: '552359783668',
    projectId: 'ymkstore-1f8b8',
    databaseURL: 'https://ymkstore-1f8b8-default-rtdb.firebaseio.com',
    storageBucket: 'ymkstore-1f8b8.appspot.com',
    iosClientId: '552359783668-75rcor5ibeem34d9bc4rd6mpfoc576no.apps.googleusercontent.com',
    iosBundleId: 'com.example.ymkStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe7D84S24BELMiqOsDteZ-HURA5aEMml4',
    appId: '1:552359783668:ios:d4308d45514149e30902a1',
    messagingSenderId: '552359783668',
    projectId: 'ymkstore-1f8b8',
    databaseURL: 'https://ymkstore-1f8b8-default-rtdb.firebaseio.com',
    storageBucket: 'ymkstore-1f8b8.appspot.com',
    iosClientId: '552359783668-75rcor5ibeem34d9bc4rd6mpfoc576no.apps.googleusercontent.com',
    iosBundleId: 'com.example.ymkStore',
  );
}
