// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATXHVad4u_mNuNH-L-4JLl61OQkxAjNf0',
    appId: '1:195881973020:web:8cd3cf22a7e1792caeb6d9',
    messagingSenderId: '195881973020',
    projectId: 'ymkstore-746da',
    authDomain: 'ymkstore-746da.firebaseapp.com',
    storageBucket: 'ymkstore-746da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnYfrs35lB5O0_GUpYH3Ez-A5tFar4mUk',
    appId: '1:195881973020:android:65a54bca5d1ab91caeb6d9',
    messagingSenderId: '195881973020',
    projectId: 'ymkstore-746da',
    storageBucket: 'ymkstore-746da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwx9wdgjALKKTcSmBfICo52-c6b_qTths',
    appId: '1:195881973020:ios:01cffa4a550026e6aeb6d9',
    messagingSenderId: '195881973020',
    projectId: 'ymkstore-746da',
    storageBucket: 'ymkstore-746da.appspot.com',
    androidClientId: '195881973020-f3fg7us2qotfpbgi1jkjc6bqie015nd5.apps.googleusercontent.com',
    iosClientId: '195881973020-hv3uljh5u110btjr2uekn9r307lmboej.apps.googleusercontent.com',
    iosBundleId: 'com.example.ymkStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwx9wdgjALKKTcSmBfICo52-c6b_qTths',
    appId: '1:195881973020:ios:01cffa4a550026e6aeb6d9',
    messagingSenderId: '195881973020',
    projectId: 'ymkstore-746da',
    storageBucket: 'ymkstore-746da.appspot.com',
    androidClientId: '195881973020-f3fg7us2qotfpbgi1jkjc6bqie015nd5.apps.googleusercontent.com',
    iosClientId: '195881973020-hv3uljh5u110btjr2uekn9r307lmboej.apps.googleusercontent.com',
    iosBundleId: 'com.example.ymkStore',
  );
}
